Smoke Test 13

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -262,9 +262,18 @@ jobs:
             echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
             echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
             echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+            echo "npm install"
             npm install
+            echo $?
+            echo "npm audit fix"
+            npm audit fix
+            echo $?
+            echo "npm run build"
             npm run build
+            echo $?
+            echo "npm migrations"
             npm run migrations > migrations_dump.txt
+            echo $?
             echo "----------------------------------"
             cat migrations_dump.txt 
             echo "----------------------------------"
@@ -273,7 +282,10 @@ jobs:
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
+              echo 'Migrated successfully'
               curl https://kvdb.io/LviPqy5qisYxGyhZgEXfxL/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            else:
+              echo 'Migration failed'
             fi
     # Here's where you will add some code to rollback on failure    
       - destroy-environment  
